site_name: National PID recommendations for research - Sweden
repo_url: https://github.com/snd-sweden/national-pid-recommendations-for-research/
repo_name: national-pid-recommendations-for-research
#docs_dir: './pid/'
copyright: 'Swedish National Data Service & other contributors 2025 | <a href="https://creativecommons.org/licenses/by/4.0/deed.en">CC-BY 4.0</a>'

theme:
    name: material
    language: en
    logo: img/snd.svg
    palette:
        primary: white
        accent: indigo
    features:
        - header.autohide
        - navigation.top
        - navigation.footer
        - navigation.tabs
        - search.suggest
        - search.highlight

extra:
#    extra.article_nav_top: false
#    extra.article_nav_bottom: true
#    extra.history_buttons: false
#    extra.logo: 'img/snd.svg'
#    extra.version: '0.0.1'
    generator: false
    social:
    - icon: fontawesome/solid/house 
      link: https://snd.se
    - icon: fontawesome/brands/github 
      link: https://github.com/snd-sweden
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/2228489365
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@svensknationelldatatjanst8231

plugins:
    - search: {}
    - bibtex:
        bib_file: "refs.bib"
        csl_file: "ieee.csl"
        bib_by_default: true

markdown_extensions:
    - toc:
        permalink: true
    - footnotes

nav:
    - National PID recommendations for research: index.md
    - PID concepts:
        - pid-concepts/index.md
        - What is a PID?: pid-concepts/what-is-pid.md
        - Persistence: pid-concepts/persistence.md
        - Uniqueness: pid-concepts/uniqueness.md
#        - Resolvability: pid-concepts/resolvability.md
#        - Interpretability: pid-concepts/interpretability.md
#        - Coverage: pid-concepts/coverage.md
        - Usage context: pid-concepts/usage-context.md
        - PID ecosystem: pid-concepts/pid-ecosystem.md
        - Kernel metadata: pid-concepts/kernel-metadata.md
        - Concept PIDs: pid-concepts/concept-pids.md
        - Landing pages: pid-concepts/landing-pages.md
        - Tombstone pages: pid-concepts/tombstone-pages.md
    - Landscape analysis:
        - landscape-analysis/index.md
        - Researchers & contributors: landscape-analysis/researchers-contributors.md
        - Organisations: landscape-analysis/organisations.md
        - Publications: landscape-analysis/publications.md
#        - Data: landscape-analysis/research-data.md
#        - Projects & activities: landscape-analysis/projects-activities.md
#        - Funding: landscape-analysis/funding.md
#        - Software & models: landscape-analysis/software-models.md
#        - Simulations: landscape-analysis/simulations.md
#        - Analyses: landscape-analysis/analyses.md
#        - Data repositories: landscape-analysis/data-repositories.md
#        - Research infrastructures: landscape-analysis/research-infrastructures.md
        - Citations: landscape-analysis/citations.md
#        - Conferences: landscape-analysis/conferences.md
#        - Instruments & collection equipment: landscape-analysis/instruments.md
#        - Samples: landscape-analysis/samples.md
#        - Protocols: landscape-analysis/protocols.md
#        - Workflows: landscape-analysis/workflows.md
#        - Preregistrations: landscape-analysis/preregistrations.md
        - Licenses: landscape-analysis/licenses.md
#        - Artefacts & finds: landscape-analysis/artefacts.md
#        - Monuments: landscape-analysis/monuments.md
#    - Recommendations: 
#        - recommendations/index.md
    - Data on PIDs:
        - data-on-pids/index.md
        - DOI: data-on-pids/doi.md
        - Handle: data-on-pids/handle.md
        - ORCID: data-on-pids/orcid.md
        - ROR ID: data-on-pids/ror.md
        - URN:NBN: data-on-pids/nbn.md
    - PID actors in Sweden:
        - pid-actors-sweden/index.md
        - Sunet: pid-actors-sweden/sunet.md
        - National Library of Sweden (KB): pid-actors-sweden/kb.md
        - Swedish National Data Service (SND): pid-actors-sweden/snd.md
#    - Definitions: definitions/index.md
